name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - plan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trigger the workflow by Slack bot
        uses: kota65535/github-workflow-dispatch-slack-action@v1
        with:
          workflow: do-something.yml
          inputs: '{"foo":"1","bar":"2"}'
          channel: my-ci
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
